// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAwWwP6iyGfZYocjAK1N1f-3QNzI2UdZro",
      authDomain: "mycollection-7b35b.firebaseapp.com",
      projectId: "mycollection-7b35b",
      storageBucket: "mycollection-7b35b.appspot.com",
      messagingSenderId: "743253836054",
      appId: "1:743253836054:web:b889afc93a97ea33095037",
      measurementId: "G-WKY60H9Z5J");

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyAoiOKwxjjEnQrZewBsbr1Y5vq0fBvij9s',
  //   appId: '1:743253836054:web:b889afc93a97ea33095037',
  //   messagingSenderId: '743253836054',
  //   projectId: 'mycollection-7b35b',
  //   storageBucket: 'mycollection-7b35b.appspot.com',
  // );
}
